Project/Project/urls.py
from django.contrib import admin
from django.urls import include, path
import apps.bookmodule.views
import apps.usermodule.views
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include("apps.bookmodule.urls")),
    path('users/', include("apps.usermodule.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/apps/bookmodule/urls.py
from . import views
from django.urls import path , include

urlpatterns = [
    path('', views.index, name= "books.index"),
    path('list_books/', views.list_books, name= "books.list_books"),
    path('viewbook/', views.viewbook, name="books.view_one_book"),
    path('aboutus/', views.aboutus, name="books.aboutus"),
    path('html5/', views.html5, name="books.html5"),
    path('html5/links/', views.links, name="books.html5.links"),
    path('html5/text/formatting', views.viewFormat, name="books.format"),
    path('html5/listing', views.viewListing, name="books.listing"),
    path('html5/tables',views.viewTable, name="books.tables"),
    path('search/',views.viewSearch,name='books.search'),
    path('simple/query',views.simple_query,name='books.simple_query'),
    path('complex/query',views.complex_query,name='books.complex_query'),
    path('lab8/task1', views.book_list_task1, name='book_list_task1'),
    path('lab8/task2', views.book_list_task2, name='book_list_task2'),
    path('lab8/task3', views.book_list_task3, name='book_list_task3'),
    path('lab8/task4', views.book_list_task4, name='book_list_task4'),
    path('lab8/task5', views.book_list_task5, name='book_list_task5'),
    path('students/lab8/task7', views.students_per_city, name='students_per_city'),
    path('lab9_part1/booklist1', views.booklist1, name='booklist1'),
    path('lab9_part1/addbook', views.add_book, name='add_book'),
    path('lab9_part1/editbook/<int:id>', views.edit_book, name='edit_book'),
    path('lab9_part1/deletebook/<int:id>', views.delete_book, name='delete_book'),
    path('lab9_part2/booklist2/', views.booklist2, name='booklist2'),
    path('lab9_part2/addbook2/', views.add_book2, name='add_book2'),
    path('lab9_part2/editbook2/<int:id>/', views.edit_book2, name='edit_book2'),
    path('lab9_part2/deletebook2/<int:id>/', views.delete_book2, name='delete_book2'),
    path('lab10/add_student', views.add_student, name= "students.add_student"),
    path('lab10/list_student', views.list_student, name= "students.list_student"),
    path('lab10/delete_student<bID>', views.delete_student, name= "students.delete_student"),
    path('lab10/edit_student<bID>', views.edit_student, name= "students.edit_student"),
    path('lab10/add_student2', views.add_student2, name= "students.add_student2"),
    path('lab10/list_student2', views.list_student2, name= "students.list_student2"),
    path('lab10/delete_student2/<bID>', views.delete_student2, name= "students.delete_student2"),
    path('lab10/edit_student2/<bID>', views.edit_student2, name= "students.edit_student2"),
    path('lab10/addBookWithCover', views.addBookWithCover, name= "books.addBookWithCover"),
    path('lab11/homepage', views.homepage, name= "books.homepage"),
    path('lab11/register', views.register, name= "books.register"),
    path('lab11/logoutuser', views.logoutuser, name= "books.logoutuser"),
    path('lab11/loginUser', views.loginUser, name= "books.loginUser"),
    path('lab12/task1', views.lab12task1, name= "books.lab12_task1"),
    path('lab12/task2', views.lab12task2, name= "books.lab12_task2"),
    path('lab12/task3', views.lab12task3, name= "books.lab12_task3"),
    path('lab12/task4', views.lab12task4, name= "books.lab12_task4"),
    path('lab12/task5', views.lab12task5, name= "books.lab12_task5"),

]

Project/apps/bookmodule/models.py
from django.db import models

class Book(models.Model):
    title = models.CharField(max_length = 50)
    author = models.CharField(max_length = 50)
    price = models.FloatField(default = 0.0)
    edition = models.SmallIntegerField(default = 1)

class Address(models.Model):
    city = models.CharField(max_length=100)

def __str__(self):
        return self.city
    
class Student(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    address = models.ForeignKey(Address, on_delete=models.CASCADE)

class Student2(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    addresses  = models.ManyToManyField(Address)

class BookCover(models.Model):
    title = models.CharField(max_length = 50)
    coverPage = models.ImageField(upload_to='documents/')

Project/apps/bookmodule/forms.py
from django import forms
from .models import Book,Student,Address,Student2,BookCover
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'price', 'edition']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'edition': forms.NumberInput(attrs={'class': 'form-control'}),
        }
        
class StudentForm(forms.ModelForm):
    class Meta:
        model= Student
        fields='__all__'
        exclude = []
    name = forms.CharField(max_length=100,label='Name',required=True,widget=forms.TextInput())
    age = forms.IntegerField(initial=0,label='Age',required=True,widget=forms.NumberInput())
    adress=forms.ModelChoiceField(label='City',queryset=Address.objects.all(),required=True, widget=forms.Select())

class StudentForm2(forms.ModelForm):
    class Meta:
        model= Student2
        fields='__all__'
        exclude = []
    name = forms.CharField(max_length=100,label='Name',required=True,widget=forms.TextInput())
    age = forms.IntegerField(initial=0,label='Age',required=True,widget=forms.NumberInput())
    addresses=forms.ModelMultipleChoiceField(label='City',queryset=Address.objects.all(),required=True, widget=forms.CheckboxSelectMultiple())
    
class BookCoverForm(forms.ModelForm):
    class Meta:
        model= BookCover
        fields='__all__'
        exclude = []
    title = forms.CharField(max_length=100,label='Name',required=True,widget=forms.TextInput())
    coverPage = forms.ImageField(label='Cover Page',required=True,widget=forms.ClearableFileInput() )

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',
                  'password1', 'password2')

Project/apps/bookmodule/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import *
from django.db.models import Q
from django.db.models import Count, Sum, Avg, Max, Min
from .forms import BookForm,StudentForm,StudentForm2,BookCoverForm,SignUpForm
from django.contrib.auth import login,logout,authenticate
from django.contrib import messages

# Create your views here.

def index(request):

    return render(request, "bookmodule/index.html")


def list_books(request):

    return render(request, 'bookmodule/list_books.html')


def viewbook(request):

    return render(request, 'bookmodule/one_book.html')


def aboutus(request):

    return render(request, 'bookmodule/aboutus.html')


def html5(request):

    return render(request, 'bookmodule/html5.html')


def links(request):

    return render(request, 'bookmodule/links.html')



def viewFormat(request):

    return render(request, 'bookmodule/formating.html')


def viewListing(request):

    return render(request, 'bookmodule/listing.html')


def viewTable(request):

    return render(request, 'bookmodule/tables.html')


def viewSearch(request):
    if request.method == "POST":
        string = request.POST.get('keyword').lower()
        isTitle = request.POST.get('option1')
        isAuthor = request.POST.get('option2')
 # now filter
        books = __getBooksList()
        newBooks = []
        for item in books:
            contained = False
            if isTitle and string in item['title'].lower(): contained = True
            if not contained and isAuthor and string in item['author'].lower():contained = True
            if contained: newBooks.append(item)
        return render(request, 'bookmodule/bookList.html', {'books':newBooks})

    return render(request,'bookmodule/search.html')
    


def __getBooksList():
    book1 = {'id':12344321, 'title':'Continuous Delivery', 'author':'J.Humble and D. Farley'}
    book2 = {'id':56788765,'title':'Reversing: Secrets of Reverse Engineering', 'author':'E. Eilam'}
    book3 = {'id':43211234, 'title':'The Hundred-Page Machine Learning Book', 'author':'Andriy Burkov'}
    return [book1, book2, book3]


def simple_query(request):
    mybooks=Book.objects.filter(title__icontains='and') # <- multiple objects
    return render(request, 'bookmodule/bookList.html', {'books':mybooks})


def complex_query(request):
    mybooks=books=Book.objects.filter(author__isnull = False).filter(title__icontains='and').filter(edition__gte = 2).exclude(price__lte = 100)[:10]
    if len(mybooks)>=1: 
        return render(request, 'bookmodule/bookList.html', {'books':mybooks})
    else:
        return render(request, 'bookmodule/index.html')

def book_list_task1(request):
    books = Book.objects.filter(Q(price__lte=50))
    return render(request, 'bookmodule/book_list_task1.html', {'books': books})

def book_list_task2(request):
    books = Book.objects.filter(Q(edition__gt=2) & (Q(title__icontains='qu') | Q(author__icontains='qu')))
    return render(request, 'bookmodule/book_list_task2.html', {'books': books})

def book_list_task3(request):
    books = Book.objects.filter(~Q(edition__gt=2) & ~Q(title__icontains='qu') & ~Q(author__icontains='qu'))
    return render(request, 'bookmodule/book_list_task3.html', {'books': books})

def book_list_task4(request):
    books = Book.objects.all().order_by('title')
    return render(request, 'bookmodule/book_list_task4.html', {'books': books})

def book_list_task5(request):
    book_stats = Book.objects.aggregate(
        total_books=Count('id'),
        total_price=Sum('price'),
        average_price=Avg('price'),
        max_price=Max('price'),
        min_price=Min('price')
    )
    return render(request, 'bookmodule/book_list_task5.html', {'book_stats': book_stats})

def students_per_city(request):
    students_count = Address.objects.annotate(student_count=Count('student')).values('city', 'student_count')
    return render(request, 'bookmodule/students_per_city.html', {'students_count': students_count})

def booklist1(request):
    books = Book.objects.all()
    return render(request, 'bookmodule/booklist1.html', {'books': books})

def add_book(request):
    if request.method == "POST":
        title = request.POST.get('title')
        author = request.POST.get('author')
        price = float(request.POST.get('price'))
        edition = int(request.POST.get('edition'))

        Book.objects.create(
            title=title,
            author=author,
            price=price,
            edition=edition
        )
        return redirect('/books/lab9_part1/booklist1')

    return render(request, 'bookmodule/add_book.html')

def edit_book(request, id):
    book = get_object_or_404(Book, id=id)

    if request.method == "POST":
        book.title = request.POST.get('title')
        book.author = request.POST.get('author')
        book.price = float(request.POST.get('price'))
        book.edition = int(request.POST.get('edition'))
        book.save()
        return redirect('/books/lab9_part1/booklist1')

    return render(request, 'bookmodule/edit_book.html', {'book': book})

def delete_book(request, id):
    book = get_object_or_404(Book, id=id)
    book.delete()
    return redirect('/books/lab9_part1/booklist1')


def booklist2(request):
    books = Book.objects.all()
    return render(request, 'bookmodule/booklist2.html', {'books': books})

def add_book2(request):
    form = BookForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect('/books/lab9_part2/booklist2')
    return render(request, 'bookmodule/add_book2.html', {'form': form})

def edit_book2(request, id):
    book = get_object_or_404(Book, id=id)
    form = BookForm(request.POST or None, instance=book)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect('/books/lab9_part2/booklist2')
    return render(request, 'bookmodule/edit_book2.html', {'form': form, 'book': book})

def delete_book2(request, id):
    book = get_object_or_404(Book, id=id)
    if request.method == "POST":
        book.delete()
        return redirect('/books/lab9_part2/booklist2')
    return render(request, 'bookmodule/delete_book2.html', {'book': book})

def list_student(request):
    students =Student.objects.all()
    return render(request,'bookmodule/list_student.html',{'students':students})      

def add_student(request):
    form=StudentForm()
    if request.method=='POST':
        form=StudentForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect('students.list_student')
    return render(request,'bookmodule/add_student.html',{'form':form})



def edit_student(request,bID):
    student = Student.objects.get(id=bID)
    if request.method=='POST':
        form = StudentForm(request.POST,instance=student)
        if form.is_valid:
            form.save()
            return redirect('students.list_student')
    form = StudentForm(instance=student)
    return render(request,'bookmodule/add_student.html',{'form':form})


def delete_student(request,bID):
    student = Student.objects.get(id=bID)
    student.delete()
    return redirect('students.list_student')

def list_student2(request):
    if request.user.is_authenticated:
        students = Student2.objects.all()
        return render(request,'bookmodule/list_student2.html',{'students':students})  
    else:
        return redirect(register)     

def add_student2(request):
    if request.user.is_authenticated:
        if request.method=='POST':
            form=StudentForm2(request.POST)
            if form.is_valid:
                form.save()
                return redirect('students.list_student2')
        else:
            form=StudentForm2()
            return render(request,'bookmodule/add_student.html',{'form':form})
    else:
        return redirect(register)    



def edit_student2(request,bID):
    if request.user.is_authenticated:
        student = Student2.objects.get(id=bID)
        if request.method=='POST':
            form = StudentForm2(request.POST,instance=student)
            if form.is_valid:
                form.save()
                return redirect('students.list_student2')
        form = StudentForm2(instance=student)
        return render(request,'bookmodule/add_student.html',{'form':form})
    else:
        return redirect(register)


def delete_student2(request,bID):
    if request.user.is_authenticated:
        student = Student2.objects.get(id=bID)
        student.delete()
        return redirect('students.list_student2')
    else:
        return redirect(register)

def addBookWithCover(request):
    if request.method=='POST':
        form = BookCoverForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            books =BookCover.objects.all()
            return render(request,'bookmodule/listBooksCovers.html',{'books':books})
        else:
            print(form.errors)

    form = BookCoverForm(None)
    return render(request,'bookmodule/addbookcover.html',{'form':form})

def homepage(request):
    return redirect(list_student2)





def register(request):
    form =SignUpForm()
    if request.method=='POST':
        form=SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)

            login(request, user)
            messages.success(request, "You Have Successfully Registered!")
            return redirect(homepage)
        else:
            messages.error(request, form.error_messages)
    return render(request,'bookmodule/register.html',{'form':form})



def logoutuser(request):
    logout(request)
    messages.success(request,"You have been logged out")
    return redirect(register)


def loginUser(request):

Project/apps/templates/bookmodule/add_student2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Student</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 50%;
            margin: 50px auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
        }

        h1 {
            text-align: center;
            color: #333;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            font-weight: bold;
            color: #333;
            display: block;
            margin-bottom: 8px;
        }

        input, select, textarea {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
            font-size: 16px;
        }

        .form-group select {
            height: 40px;
        }

        .form-group input[type="checkbox"] {
            width: auto;
        }

        .form-group input[type="submit"] {
            background-color: #4CAF50;
            color: white;
            border: none;
            cursor: pointer;
            padding: 12px 20px;
            font-size: 16px;
            border-radius: 5px;
            width: auto;
            display: block;
            margin: 20px auto;
        }

        .form-group input[type="submit"]:hover {
            background-color: #45a049;
        }

        .back-link {
            text-align: center;
            display: block;
            margin-top: 20px;
        }

        .back-link a {
            color: #4CAF50;
            text-decoration: none;
            font-size: 16px;
        }

        .back-link a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Add New Student</h1>

        <!-- Form for adding student -->
        <form method="POST">
            {% csrf_token %}
            
            <div class="form-group">
                <label for="id_name">Name</label>
                {{ form.name }}
            </div>

            <div class="form-group">
                <label for="id_age">Age</label>
                {{ form.age }}
            </div>

            <div class="form-group">
                <label for="id_addresses">Addresses</label>
                {{ form.addresses }}
            </div>

            <div class="form-group">
                <input type="submit" value="Add Student">
            </div>
        </form>

        <!-- Link to go back to the student list -->
        <div class="back-link">
            <a href="{% url 'students.list_student2' %}">Back to Students List</a>
        </div>
    </div>
</body>
</html>

Project/apps/templates/bookmodule/book_list_task3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book List Task 3</title>
</head>
<body>
    <h1>Books with No Editions Higher Than Two and No 'qu' in Title or Author</h1>
    <ul>
        {% for book in books %}
            <li>{{ book.title }} by {{ book.author }} - Edition {{ book.edition }}</li>
        {% empty %}
            <p>No books found matching the criteria.</p>
        {% endfor %}
    </ul>
</body>
</html>

Project/apps/templates/bookmodule/book_list_task5.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Statistics</title>
</head>
<body>
    <h1>Book Statistics</h1>
    <ul>
        <li>Total Number of Books: {{ book_stats.total_books }}</li>
        <li>Total Price of All Books: ${{ book_stats.total_price }}</li>
        <li>Average Price of Books: ${{ book_stats.average_price }}</li>
        <li>Maximum Price of a Book: ${{ book_stats.max_price }}</li>
        <li>Minimum Price of a Book: ${{ book_stats.min_price }}</li>
    </ul>
</body>
</html>

Project/apps/templates/bookmodule/booklist2.html
<!DOCTYPE html>
<html>
<head>
    <title>Book List</title>
</head>
<body>
    <h1>Book List</h1>
    <a href="/books/lab9_part2/addbook2/">Add New Book</a>
    <ul>
        {% for book in books %}
        <li>
            {{ book.title }} by {{ book.author }} - ${{ book.price }} (Edition {{ book.edition }})
            <a href="/books/lab9_part2/editbook2/{{ book.id }}/">Edit</a>
            <a href="/books/lab9_part2/deletebook2/{{ book.id }}/">Delete</a>
        </li>
        {% endfor %}
    </ul>
{% if form %}
    <h2>{% if book %}Edit Book{% else %}Add New Book{% endif %}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{{ button_text }}</button>
    </form>
{% endif %}
</body>
</html>

Project/apps/templates/bookmodule/deletebook2.html
<!DOCTYPE html>
<html>
<head>
    <title>Delete Book</title>
</head>
<body>
    <h1>Are you sure you want to delete "{{ book.title }}"?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, Delete</button>
    </form>
    <a href="/books/lab9_part2/booklist2/">Cancel</a>
</body>
</html>

Project/apps/templates/bookmodule/edit_book.html
<!DOCTYPE html>
<html>
<head>
    <title>Edit Book</title>
</head>
<body>
    <h1>Edit Book</h1>
    <form method="post">
        {% csrf_token %}
        <label>Title:</label><br>
        <input type="text" name="title" value="{{ book.title }}" required><br>
        <label>Author:</label><br>
        <input type="text" name="author" value="{{ book.author }}" required><br>
        <label>Price:</label><br>
        <input type="number" step="0.01" name="price" value="{{ book.price }}" required><br>
        <label>Edition:</label><br>
        <input type="number" name="edition" value="{{ book.edition }}" required><br>
        <button type="submit">Update Book</button>
    </form>
</body>
</html>

Project/apps/templates/bookmodule/edit_book2.html
<!DOCTYPE html>
<html>
<head>
    <title>Edit Book</title>
</head>
<body>
    <h1>Edit Book</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
    <a href="/books/lab9_part2/booklist2/">Back to List</a>
</body>
</html>

Project/apps/templates/bookmodule/homePage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home page</title>
</head>
<body>



      {% if user.is_authenticated %}
      <a href="{% url 'books.logoutuser' %}">Logout</a>
      {% else %}

      <a href="{% url 'books.register' %}">Register</a>
      <a href="{% url 'books.loginUser' %}">Login</a>

    {% endif %}
</body>
</html>

Project/apps/templates/bookmodule/lab12_task2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task 2</title>
</head>
<body>
    <h2>Task 2: Add List Item</h2>
    <button id="addItemButton">Add New Item</button>
    <ul id="list">
        <li>Item 1</li>
        <li>Item 2</li>
    </ul>

    <script>
        document.getElementById('addItemButton').onclick = function() {
            const newItem = document.createElement('li');
            newItem.textContent = 'New Item';
            document.getElementById('list').appendChild(newItem);
        };
    </script>
</body>
</html>

Project/apps/templates/bookmodule/lab12_task4.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task 4</title>
</head>
<body>
    <h2>Task 4: Change Style on Mouse Hover</h2>
    <div id="hoverDiv" style="width: 300px; height: 200px; background-color: lightgreen;">
        <p>Hover over this div to change its style.</p>
    </div>

    <script>
        const hoverDiv = document.getElementById('hoverDiv');

        hoverDiv.onmouseover = function() {
            hoverDiv.style.backgroundColor = "lightyellow";
            hoverDiv.style.fontSize = "20px";
        };

        hoverDiv.onmouseout = function() {
            hoverDiv.style.backgroundColor = "lightgreen";
            hoverDiv.style.fontSize = "16px";
        };
    </script>
</body>
</html>

Project/apps/templates/bookmodule/listBooksCovers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>View Books</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 80%;
            margin: 30px auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
        }

        h1 {
            text-align: center;
            color: #333;
        }

        .button {
            background-color: #4CAF50;
            color: white;
            padding: 10px 15px;
            border: none;
            text-decoration: none;
            border-radius: 5px;
            font-size: 16px;
            display: inline-block;
            margin: 20px 0;
            text-align: center;
        }

        .button:hover {
            background-color: #45a049;
        }

        table {
            width: 100%;
            margin-top: 20px;
            border-collapse: collapse;
            table-layout: auto;
        }

        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
            font-size: 16px;
        }

        th {
            background-color: #f2f2f2;
            color: #333;
        }

        tr:hover {
            background-color: #f9f9f9;
        }

        td {
            word-wrap: break-word;
            max-width: 250px;
            overflow: hidden;
            text-overflow: ellipsis;
        }

        .back-link {
            display: block;
            text-align: center;
            margin-top: 20px;
        }

        .back-link a {
            color: #4CAF50;
            text-decoration: none;
            font-size: 16px;
        }

        .back-link a:hover {
            text-decoration: underline;
        }
    </style>
</head>

<body>
    <div class="container">
        <h1>Books List</h1>
        
        <a href="{% url 'books.addBookWithCover' %}" class="button">Add Book</a>
        
        <table>
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Cover Path</th>
                </tr>
            </thead>
            <tbody>
                {% for book in books %}
                    <tr>
                        <td>{{ book.title }}</td>
                        <td>{{ book.coverPage }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="back-link">
            <a href="{% url 'books.booklist1' %}">Back to Books List</a>
        </div>
    </div>
</body>
</html>

Project/apps/templates/bookmodule/one_book.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
 <title>Show one Book</title>
 <meta name="keywords" content="Books, recent, Learning, library">
 <meta name="description" content="Books website">
 <meta name="author" content="author name">
 <link rel="icon" href="{% static 'qu-icon.jpeg' %}">
 <link rel="stylesheet" href="{% static 'styles.css' %}">
 <meta charset="UTF-8">
</head>
<body>
<a href="{% url "books.list_books" %}">Go Back</a>
<h1>Details of Book1</h1>
<h2>ISoul</h2>
<h2>Author: author name</h2>
<p><strong> Soul, 5/e </strong> The life that Kim and Krickitt Carpenter knew changed completely on November 24, 1993, two months after their wedding,
     when the back of their car was struck by a speeding pickup truck. A serious head injury left Krickitt in a coma for several weeks. When she finally woke up,
      part of her memory was impaired and she could not remember her husband. She had no idea who he was. Essentially, the "Krickitt" that Kim had married had died in the accident, and now he needed to win back the woman he loved..</p>
<img src="{% static 'book1.jpeg' %}" alt="Book1 img desc" width="200" height="200">
</body>
</html>

Project/apps/templates/bookmodule/students_per_city.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Students Per City</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        h1 {
            text-align: center;
            margin-top: 20px;
            color: #333;
        }
        table {
            width: 60%;
            margin: 20px auto;
            border-collapse: collapse;
            background-color: white;
        }
        th, td {
            padding: 10px;
            text-align: center;
            border: 1px solid #ddd;
        }
        th {
            background-color: #4CAF50;
            color: white;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        tr:hover {
            background-color: #ddd;
        }
        .no-data {
            text-align: center;
            font-style: italic;
        }
    </style>
</head>
<body>
    <h1>Number of Students in Each City</h1>
    <table>
        <thead>
            <tr>
                <th>City</th>
                <th>Number of Students</th>
            </tr>
        </thead>
        <tbody>
            {% for record in students_per_city %}
                <tr>
                    <td>{{ record.city }}</td>
                    <td>{{ record.student_count }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="2" class="no-data">No data available</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>